import time

from ir import Directive, ImmLabel, ImmValue, Instruction, LabelDecl

opts = []


def optimize(ast):
    global opts
    logs = []
    opt_pass_times = []
    # Multiple passes to allow optimizations that enable other optimizations (e.g. removing a jump may enable removal of unreachable code after it, or folding offset calcs may enable removal of now-redundant instructions). In practice, 2-3 passes should be sufficient for most cases, and we can always increase if needed.
    # Very quickly diminishing returns after about 2 passes
    # But it's quick enough that we can afford to be generous with the number of passes.
    previous_ast = None
    ran_passes = 0
    for _ in range(
        10
    ):  # Limit the number of passes to prevent infinite loops (Shouldn't be possible, but just in case)
        t0 = time.perf_counter_ns()
        previous_ast = ast
        for opt in opts:
            ast = opt(ast, logs)
        if ast == previous_ast:
            break
        ran_passes += 1
        opt_pass_times.append(time.perf_counter_ns() - t0)
    logs.append(
        f"Optimization complete in {sum(opt_pass_times)/1e6:.2f} ms over {len(opts)} optimizations and {ran_passes} passes (individual pass times: {[f'{t/1e6:.2f} ms' for t in opt_pass_times]})"
    )
    return ast, logs


def _mark_optimized(node):
    if isinstance(node, Instruction):
        return node.copy_with(is_optimized=True)
    return node


def opt_40_remove_unneeded_moves(ast, logs):
    #   OR r10, r10, r11    // binop |
    #   ADDI r4, r10, 0    // assign lfsr
    # can be optimized to:
    # OR r4, r10, r11
    optimized_ast = []
    for instr in ast:
        if (
            isinstance(instr, Instruction)
            and instr.name
            in {"addi"}  # ADDI is the only move instruction generated by the compiler.
            # Theoretically, this could also be done for other I type instructions, but it's likely not worth it.
            and instr.type == "i"
        ):
            rd = instr.rd
            rs = instr.rs1
            imm = instr.imm
            if _reg_from_imm(imm) == 0:
                # Check if previous instruction is a binop that writes to rs
                if optimized_ast:
                    prev = optimized_ast[-1]
                    if (
                        isinstance(prev, Instruction)
                        and prev.rd == rs
                        and prev.name in {"or", "and", "xor", "add", "sub"}
                    ):
                        # Create new instruction with rd of current and operands of previous
                        new_instr = prev.copy_with(rd=rd, is_optimized=True)
                        optimized_ast[-1] = new_instr
                        logs.append(
                            f"Removed unneeded move by combining '{prev}' and '{instr}' into '{new_instr}' at index {len(optimized_ast)-1}"
                        )
                        continue
        optimized_ast.append(instr)
    return optimized_ast


def opt_30_remove_unneeded_jumps(ast, logs):
    # Remove jumps that are immediately followed by their target label
    optimized_ast = []
    i = 0
    while i < len(ast):
        instr = ast[i]
        if _is_jmp_to_label(instr):
            imm = instr.imm
            target = imm.name if isinstance(imm, ImmLabel) else None

            if target is not None:
                j = i + 1
                while j < len(ast) and isinstance(ast[j], LabelDecl):
                    if ast[j].name == target:
                        logs.append(
                            f"Removed unneeded jmp pseudo before label '{target}' at index {i}"
                        )
                        i += 1
                        break
                    j += 1
                else:
                    optimized_ast.append(instr)
                    i += 1
                    continue

                continue
        optimized_ast.append(instr)
        i += 1
    return optimized_ast


def _reg_from_imm(imm):
    if isinstance(imm, ImmValue):
        return int(imm.value)
    try:
        return int(imm)
    except Exception:
        return None


def opt_30_nop_removal(ast, logs):
    # E.g. ADDI r5, r5, 0
    optimized_ast = []
    for instr in ast:
        if (
            isinstance(instr, Instruction)
            and instr.name in {"addi", "ori", "subi"}
            and instr.type == "i"
        ):
            rd = instr.rd
            rs = instr.rs1
            imm = instr.imm
            if rd == rs and _reg_from_imm(imm) == 0:
                logs.append(
                    f"Removed effective NOP instruction '{instr}' at index {len(optimized_ast)}"
                )
                continue
        optimized_ast.append(instr)
    return optimized_ast


def opt_30_condition_against_zero(ast, logs):
    #   LLI rX, 0
    #   BEQ/BNE a, rX, label
    # or
    #   LLI rX, 0
    #   BEQ/BNE rX, a, label
    # =>
    #   BEQ/BNE a, r0, label   (or r0, a depending on operand order)
    optimized_ast = []
    i = 0

    def _is_zero_lli(node):
        return (
            isinstance(node, Instruction)
            and node.type == "p"
            and node.name == "lli"
            and node.rd is not None
            and _reg_from_imm(node.imm) == 0
        )

    def _is_eq_ne_branch(node):
        return (
            isinstance(node, Instruction)
            and node.type == "b"
            and node.name in {"beq", "bne"}
            and node.rd is not None
            and node.rs1 is not None
        )

    while i < len(ast):
        if i + 1 < len(ast) and _is_zero_lli(ast[i]) and _is_eq_ne_branch(ast[i + 1]):
            lli = ast[i]
            br = ast[i + 1]
            loaded_reg = lli.rd

            lhs = br.rd
            rhs = br.rs1
            if lhs == loaded_reg or rhs == loaded_reg:
                new_br = br.copy_with(
                    rd=0 if lhs == loaded_reg else lhs,
                    rs1=0 if rhs == loaded_reg else rhs,
                    is_optimized=True,
                )
                optimized_ast.append(new_br)
                logs.append(
                    f"Optimized condition-against-zero at indices {i}-{i+1}: "
                    f"replaced '{lli}' and '{br}' with '{new_br}'"
                )
                i += 2
                continue

        optimized_ast.append(ast[i])
        i += 1

    return optimized_ast


def opt_20_push_pop(ast, logs):
    # find sequences of push and pop instructions that cancel each other out and eliminate them
    # e.g.
    # PUSH r1
    # PUSH r2
    # PUSH r3
    # POP r3
    # POP r2
    # POP r1
    # While this technically does write r1, r2, r3 to the stack (and therefore, this does change the program's behavior), you shouldn't really try reading from the stack directly anyways, and even if you do, this *shouldn't* cause any issues.

    # This is commonly generated from two successive calls, where the first call pushes arguments onto the stack, then calls a function which pops those arguments, and then the second call pushes new arguments onto the stack. In this case, we can safely eliminate the middle pushes and pops, as they shouldn't have any effect on the program's behavior. This is a common pattern that we can optimize away.
    optimized_ast = []
    i = 0
    while i < len(ast):
        instr = ast[i]

        # Check if current instruction is a pop
        if isinstance(instr, Instruction) and instr.name == "pop" and instr.type == "p":
            pop_sequence = [instr]
            j = i + 1

            # Collect consecutive pops
            while (
                j < len(ast)
                and isinstance(ast[j], Instruction)
                and ast[j].name == "pop"
                and ast[j].type == "p"
            ):
                pop_sequence.append(ast[j])
                j += 1

            # Check if followed by push sequence
            push_sequence = []
            while (
                j < len(ast)
                and isinstance(ast[j], Instruction)
                and ast[j].name == "push"
                and ast[j].type == "p"
            ):
                push_sequence.append(ast[j])
                j += 1

            # If we have both pops and pushes, try to match them
            if pop_sequence and push_sequence:
                # Create lists of immediate values
                pop_values = [_reg_from_imm(p.imm) for p in pop_sequence]
                push_values = [_reg_from_imm(p.imm) for p in push_sequence]

                # Check if push values are reverse of pop values (stack property)
                if push_values == list(reversed(pop_values)):
                    # Perfect match - eliminate both sequences
                    logs.append(
                        f"Removed POP/PUSH cancellation block at indices {i}-{j-1} (len={len(pop_sequence) + len(push_sequence)})"
                    )
                    if j < len(ast):
                        optimized_ast.append(_mark_optimized(ast[j]))
                        i = j + 1
                        continue
                    i = j
                    continue

            # No match, keep the pop instruction
            optimized_ast.append(instr)
            i += 1
        else:
            # Not a pop, keep instruction as-is
            optimized_ast.append(instr)
            i += 1

    return optimized_ast


def _is_jmp_to_label(instr):
    return (
        isinstance(instr, Instruction)
        and instr.name == "jmp"
        and (instr.rd is None or instr.rd == 0)
        and isinstance(getattr(instr, "imm", None), ImmLabel)
    )


def _next_non_label_index(ast, idx):
    while idx < len(ast) and isinstance(ast[idx], LabelDecl):
        idx += 1
    return idx


def opt_30_thread_jump_chains(ast, logs):
    # If jmp A and A immediately jumps to B, rewrite to jmp B
    label_to_index = {}
    for idx, node in enumerate(ast):
        if isinstance(node, LabelDecl):
            label_to_index[node.name] = idx

    optimized_ast = []
    for idx, instr in enumerate(ast):
        if not _is_jmp_to_label(instr):
            optimized_ast.append(instr)
            continue

        original = instr.imm.name
        target = original
        visited = set()

        while target in label_to_index and target not in visited:
            visited.add(target)
            k = _next_non_label_index(ast, label_to_index[target] + 1)
            if k < len(ast) and _is_jmp_to_label(ast[k]):
                target = ast[k].imm.name
            else:
                break

        if target != original:
            logs.append(f"Threaded jump at index {idx}: '{original}' -> '{target}'")
            optimized_ast.append(
                instr.copy_with(imm=ImmLabel(target), is_optimized=True)
            )
        else:
            optimized_ast.append(instr)

    return optimized_ast


def opt_30_remove_unreachable_after_jmp(ast, logs):
    # Remove straight-line code after an unconditional jmp until next label
    optimized_ast = []
    i = 0
    while i < len(ast):
        node = ast[i]
        optimized_ast.append(node)
        i += 1

        if _is_jmp_to_label(node):
            while i < len(ast) and not isinstance(ast[i], LabelDecl):
                logs.append(
                    f"Removed unreachable instruction '{ast[i]}' after jmp at index {i-1}"
                )
                i += 1

    return optimized_ast


def _find_used_labels(ast):
    used_labels = set()
    for instr in ast:
        if isinstance(instr, Instruction) and hasattr(instr, "imm"):
            imm = instr.imm
            if isinstance(imm, ImmLabel):
                used_labels.add(imm.name)
    return used_labels


def _find_defined_labels(ast):
    defined_labels = set()
    for instr in ast:
        if isinstance(instr, LabelDecl):
            defined_labels.add(instr.name)
    return defined_labels


def opt_35_redundant_reload_to_move(ast, logs):
    # Example:
    #   LB r3, r1, 0
    #   BEQ r3, r0, L
    #   LB r4, r1, 0
    # =>
    #   LB r3, r1, 0
    #   BEQ r3, r0, L
    #   ADDI r4, r3, 0
    optimized_ast = []
    i = 0
    while i < len(ast):
        if i + 2 >= len(ast):
            optimized_ast.append(ast[i])
            i += 1
            continue

        a = ast[i]
        mid = ast[i + 1]
        b = ast[i + 2]

        is_load_a = (
            isinstance(a, Instruction)
            and a.type == "l"
            and a.name in {"lb", "lbu", "lh", "lhu", "lw"}
            and a.rd is not None
            and a.rs1 is not None
            and _reg_from_imm(a.imm) is not None
        )
        is_load_b = (
            isinstance(b, Instruction)
            and b.type == "l"
            and b.name == getattr(a, "name", None)
            and b.rd is not None
            and b.rs1 == getattr(a, "rs1", None)
            and _reg_from_imm(b.imm) == _reg_from_imm(getattr(a, "imm", None))
        )
        is_safe_mid = isinstance(mid, Instruction) and mid.type == "b"

        if is_load_a and is_load_b and is_safe_mid:
            replacement = Instruction(
                type="i",
                name="addi",
                rd=b.rd,
                rs1=a.rd,
                imm=ImmValue(0),
                src=b.src,
                is_optimized=True,
                is_from_rospocc=b.is_from_rospocc,
                is_pseudo_expanded=b.is_pseudo_expanded,
                expansion_depth=b.expansion_depth,
            )
            optimized_ast.extend([a, mid, replacement])
            logs.append(
                f"Replaced redundant reload '{b}' at index {i+2} with '{replacement}'"
            )
            i += 3
            continue

        optimized_ast.append(a)
        i += 1

    return optimized_ast


def opt_30_remove_unused_labels(ast, logs):
    used_labels = _find_used_labels(ast)
    defined_labels = _find_defined_labels(ast)
    unused_labels = defined_labels - used_labels

    optimized_ast = []
    for instr in ast:
        if isinstance(instr, LabelDecl) and instr.name in unused_labels:
            logs.append(
                f"Removed unused label '{instr.name}' at index {len(optimized_ast)}"
            )
            continue
        optimized_ast.append(instr)

    return optimized_ast


def opt_30_combine_safe_offset_calcs(ast, logs):
    #   LLI r12, 3    // load immediate 3
    #   ADD r12, r1, r12    // binop +
    #   LLI r5, 255    // load immediate 255
    #   AND r2, r2, r5    // binop &
    #   SB r2, r12, 0    // intrinsic __sb
    # Because the AND instruction doesn't affect the offset calculation in r12,
    # we can safely combine the offset calculation with the store instruction,
    # eliminating the need for r12 and the AND instruction.
    # That is, we can optimize this to:
    # LLI r5, 255    // load immediate 255
    # AND r2, r2, r5    // binop &
    #  SB r2, r1, 3    // intrinsic __sb with offset
    # Conditions:
    # - The offset calculation (e.g. ADD r12, r1, r12) must be a simple addition of a register and an immediate. (or subtraction)
    # - The register used for the offset calculation (r12) must not be used in any way between the offset calculation and the store instruction,
    # except for being the destination of the offset calculation and being used as the address register in the store instruction.
    # - The instruction that uses the offset must be either a load or store instruction
    # - The immediate value used in the offset calculation must be a constant that can be directly encoded in the store instruction's offset field
    optimized_ast = []
    i = 0

    def _is_lli_imm(instr):
        return (
            isinstance(instr, Instruction)
            and instr.type == "p"
            and instr.name == "lli"
            and instr.rd is not None
            and _reg_from_imm(instr.imm) is not None
        )

    def _is_control_flow(instr):
        return isinstance(instr, Instruction) and instr.type in {"b", "j"}

    def _is_load_or_store(instr):
        return isinstance(instr, Instruction) and instr.type == "l"

    def _uses_reg(instr, reg):
        if not isinstance(instr, Instruction):
            return False
        return instr.rd == reg or instr.rs1 == reg or instr.rs2 == reg

    def _encodable_l_imm(value):
        # L-type immediates share encoding constraints with I/B/J in maps.validate_immediate_for_type.
        return -32768 <= value <= 65535

    while i < len(ast):
        lli = ast[i]

        # We only fold the canonical two-instruction address compute:
        #   LLI tmp, k
        #   ADD/SUB tmp, base, tmp
        if not _is_lli_imm(lli) or i + 1 >= len(ast):
            optimized_ast.append(lli)
            i += 1
            continue

        calc = ast[i + 1]
        if not (
            isinstance(calc, Instruction)
            and calc.type == "r"
            and calc.name in {"add", "sub"}
            and calc.rd == lli.rd
        ):
            optimized_ast.append(lli)
            i += 1
            continue

        tmp_reg = lli.rd
        imm_value = _reg_from_imm(lli.imm)
        if imm_value is None:
            optimized_ast.append(lli)
            i += 1
            continue

        base_reg = None
        offset_delta = None

        if calc.name == "add":
            if calc.rs1 == tmp_reg and calc.rs2 is not None:
                base_reg = calc.rs2
                offset_delta = imm_value
            elif calc.rs2 == tmp_reg and calc.rs1 is not None:
                base_reg = calc.rs1
                offset_delta = imm_value
        elif calc.name == "sub":
            # SUB tmp, base, tmp => base + (-imm)
            if calc.rs2 == tmp_reg and calc.rs1 is not None:
                base_reg = calc.rs1
                offset_delta = -imm_value

        if base_reg is None or offset_delta is None:
            optimized_ast.append(lli)
            i += 1
            continue

        # Scan forward until we hit a matching load/store that consumes tmp_reg as address.
        # Abort on control flow, labels/directives, or any other use/def of tmp_reg.
        j = i + 2
        folded = False
        while j < len(ast):
            node = ast[j]

            if isinstance(node, LabelDecl) or not isinstance(node, Instruction):
                break
            if _is_control_flow(node):
                break

            if _is_load_or_store(node) and node.rs1 == tmp_reg:
                existing_offset = _reg_from_imm(node.imm)
                if existing_offset is None:
                    break

                combined_offset = existing_offset + offset_delta
                if not _encodable_l_imm(combined_offset):
                    break

                # Keep instructions between calc and load/store unchanged,
                # drop lli/calc, and rewrite base+offset directly in load/store.
                optimized_ast.extend(ast[i + 2 : j])
                new_node = node.copy_with(
                    rs1=base_reg,
                    imm=ImmValue(combined_offset),
                    is_optimized=True,
                )
                optimized_ast.append(new_node)
                logs.append(
                    f"Combined safe offset calc at indices {i}-{j}: removed '{lli}' and '{calc}', rewrote '{node}' to '{new_node}'"
                )
                i = j + 1
                folded = True
                break

            if _uses_reg(node, tmp_reg):
                break

            j += 1

        if folded:
            continue

        optimized_ast.append(lli)
        i += 1

    return optimized_ast


def opt_45_push_pop_to_move(ast, logs):
    # Convert push followed by pop of a different register to a single ADDI instruction
    # PUSH r1
    # POP r2
    # =>
    # ADDI r2, r1, 0
    optimized_ast = []
    i = 0
    while i < len(ast) - 1:
        instr = ast[i]
        next_instr = ast[i + 1]

        if (
            isinstance(instr, Instruction)
            and instr.name == "push"
            and instr.type == "p"
            and isinstance(next_instr, Instruction)
            and next_instr.name == "pop"
            and next_instr.type == "p"
        ):
            push_reg = _reg_from_imm(instr.imm)
            pop_reg = _reg_from_imm(next_instr.imm)

            if push_reg is not None and pop_reg is not None:
                if push_reg != pop_reg:
                    new_instr = Instruction(
                        name="addi",
                        type="i",
                        rd=pop_reg,
                        rs1=push_reg,
                        imm=ImmValue(0),
                        is_optimized=True,
                    )
                    optimized_ast.append(new_instr)
                    logs.append(
                        f"Converted PUSH/POP to move at indices {i}-{i+1}: replaced '{instr}' and '{next_instr}' with '{new_instr}'"
                    )
                    i += 2
                    continue
                else:
                    # If push and pop are the same register, we can eliminate both as they have no effect.
                    # This *should* be caught by opt_00_push_pop, but we can also handle it here just in case.
                    logs.append(
                        f"Removed redundant PUSH/POP of same register at indices {i}-{i+1}: removed '{instr}' and '{next_instr}'"
                    )
                    i += 2
                    continue
        optimized_ast.append(instr)
        i += 1

    # Append the last instruction if it wasn't part of a pair
    if i < len(ast):
        optimized_ast.append(ast[i])

    return optimized_ast


def opt_40_space_sorting(ast, logs):
    # buffer:
    #   .SPACE 256

    # buffer_update_queue:
    #   .SPACE 64

    # buffer_update_queue_ptr:
    #   .DATA 0x00
    # !!!
    # str_0:
    #   .STR "example.txt\0"

    # ...

    # str_9:
    #   .STR "and only updates the display when necessary.\0"
    # draw_line_8_spill23:
    #   .SPACE 4 // lifted buffer

    # interleaving space and data declarations leads to suboptimal buffer packing, as .SPACE directive only *virtually*
    # increases the address of the next declaration, but doesn't actually emit any bytes.
    # This saves space, but if we have a .SPACE directive before any other declaration, it will be forced to create
    # A new section to ensure the correct address for the next declaration, which can lead to inefficient packing
    # of data and wasted space. By moving all .SPACE directives to the end of the data section, we can ensure that
    # all actual data declarations are packed together efficiently, and all the .SPACE directives are grouped together
    # At the end, which should lead to better overall packing of the data section and reduced binary size

    # Key notes:
    # We only move .SPACE directives AND THEIR ASSOCIATED LABELS. We do NOT move any other directives (e.g. .DATA, .STR) or their labels.
    # A .SPACE directive may have multiple labels (e.g. a buffer with multiple pointers to it), and we move all of those labels together with the .SPACE directive.
    # We preserve the relative order of all non-.SPACE directives and their labels.
    optimized_ast = []
    space_decls = []  # ([labels], space_directive)

    current_labels = []
    for node in ast:
        if isinstance(node, LabelDecl):
            current_labels.append(node)
        elif isinstance(node, Directive) and node.name == "space":
            space_decls.append((current_labels, node))
            current_labels = []
        else:
            optimized_ast.extend(current_labels)
            current_labels = []
            optimized_ast.append(node)
    # Append any remaining labels (if the last declaration(s) are .SPACE, they would have been collected in current_labels but not yet appended)
    optimized_ast.extend(current_labels)
    # Append .SPACE declarations at the end
    for labels, space in space_decls:
        optimized_ast.extend(labels)
        optimized_ast.append(space)
    return optimized_ast


# This is a bit of a hack to avoid having to manually maintain the list of optimizations,
# but it should work fine as long as we don't have any non-optimization functions that start with "opt_".
opts = [globals()[_] for _ in sorted(dir()) if _.startswith("opt_")]
