"""
RegisterAllocInfoReader: Reads register allocation debug info from .rosc.regalloc sidecar files.

This module provides parsing and lookup functions for register allocation metadata
generated by the compiler. This info is then encoded into debug segments.
"""

import json
from typing import Dict, List, Optional


class RegisterAllocInfo:
    """Represents register allocation info for a specific output line."""

    def __init__(
        self,
        output_line: int,
        register: str,
        variable_name: str,
        variable_type: str,
        var_kind: str = "local",
        origin: Optional[str] = None,
        action: str = "allocate",
    ):
        self.output_line = output_line
        self.register = register
        self.variable_name = variable_name
        self.variable_type = variable_type
        self.var_kind = var_kind
        self.origin = origin
        self.action = action

    def to_dict(self) -> Dict:
        return {
            "register": self.register,
            "variable_name": self.variable_name,
            "variable_type": self.variable_type,
            "var_kind": self.var_kind,
            "origin": self.origin,
            "action": self.action,
        }


class RegisterAllocInfoReader:
    """Reads and provides lookup access to register allocation info."""

    def __init__(self):
        """Initialize the reader."""
        self.allocations: List[RegisterAllocInfo] = []
        # Event index: output_line -> list of RegisterAllocInfo events at that line.
        self.line_index: Dict[int, List[RegisterAllocInfo]] = {}

    def load_from_file(self, filepath: str) -> bool:
        """
        Load register allocation info from a sidecar file.

        Args:
            filepath: Path to the .rosc.regalloc file

        Returns:
            True if successfully loaded, False on error
        """
        try:
            with open(filepath, "r") as f:
                data = json.load(f)

            if data.get("version") != 1:
                print(f"Warning: Unknown regalloc format version {data.get('version')}")
                return False

            for alloc_dict in data.get("allocations", []):
                info = RegisterAllocInfo(
                    output_line=alloc_dict.get("output_line", 0),
                    register=alloc_dict.get("register", ""),
                    variable_name=alloc_dict.get("variable_name", ""),
                    variable_type=alloc_dict.get("variable_type", "int"),
                    var_kind=alloc_dict.get("var_kind", "local"),
                    origin=alloc_dict.get("origin"),
                    action=alloc_dict.get("action", "allocate"),
                )
                self.allocations.append(info)
                # Add to line index
                if info.output_line not in self.line_index:
                    self.line_index[info.output_line] = []
                self.line_index[info.output_line].append(info)

            return True
        except FileNotFoundError:
            # No regalloc file is OK - just not provided
            return False
        except json.JSONDecodeError as e:
            print(f"Error parsing regalloc file {filepath}: {e}")
            return False
        except Exception as e:
            print(f"Error loading regalloc file {filepath}: {e}")
            return False

    def get_allocations_for_line(self, output_line: int) -> List[RegisterAllocInfo]:
        """
        Get all register allocations active at a specific output line.

        Args:
            output_line: The output line number

        Returns:
            List of RegisterAllocInfo for that line
        """
        if output_line <= 0:
            return []

        # Reconstruct active state by applying events up to this line.
        active_by_reg: Dict[str, RegisterAllocInfo] = {}
        for line in sorted(self.line_index.keys()):
            if line > output_line:
                break
            for event in self.line_index[line]:
                if event.action == "free":
                    active_by_reg.pop(event.register, None)
                else:
                    active_by_reg[event.register] = event
        return list(active_by_reg.values())

    def get_allocation_for_register(
        self, output_line: int, register: str
    ) -> Optional[RegisterAllocInfo]:
        """
        Get allocation info for a specific register at a specific line.

        Args:
            output_line: The output line number
            register: The register name

        Returns:
            RegisterAllocInfo if found, None otherwise
        """
        for info in self.get_allocations_for_line(output_line):
            if info.register == register:
                return info
        return None

    def get_all_allocations(self) -> List[RegisterAllocInfo]:
        """Get all loaded allocations."""
        return self.allocations.copy()
